# Generated by Django 5.1.4 on 2025-02-21 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="domain",
        ),
        migrations.RemoveField(
            model_name="user",
            name="company",
        ),
        migrations.AddField(
            model_name="company",
            name="schema_name",
            field=models.CharField(default="public", max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="login.company",
            ),
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="login.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
